### ISSUE TITLE
Incomplete Log Entries

### ISSUE THREAD

**Issue by Stecors** [lichess-org/fishnet#255] opened 2024-01-07 20:19 UTC
I've noticed an issue with the stdout output in Fishnet where, instead of displaying the full "finished" message, it sometimes only shows incomplete entries.

Normal Output Example:
'[=====|===========> https://lichess.org/0amiUAIw finished (2163 knps)'

Incomplete Output Example:
'[====|============> KufMqLPj finished (3674 knps)'

Appending these UIDs (e.g., 'KufMqLPj') to the Lichess URL (https://lichess.org/) results in a 404 error.

Additional examples from the output:

    2023-12-27 11:51:17 [====|============> x2tOIWKH finished (2377 knps)
    2023-12-28 14:58:30 [====|============> PyiuOviQ finished (2681 knps)
    2024-01-02 17:46:01 [====|============> Shn2F0WP finished (3103 knps)
    2024-01-02 18:08:48 [====|============> UULShE2S finished (2551 knps)
    2024-01-04 19:14:06 [====|============> VAGUzR01 finished (2527 knps)
    2024-01-07 20:31:37 [=====|===========> 7kOUtSli finished (1154 knps)

These entries are among approximately 30,000 lines of stdout output, so it's rather rare.

If this is an intended feature, feel free to close this issue.

**Comment by niklasf** [comment] 2024-01-07 21:36
The majority of batches are public games with URLs. These are internal ids assigned to batches like studies. So it's working as intended, but the output is a bit confusing.

**Closed** 2024-01-07 21:38 UTC
